//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowRoom.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarModel
    {
        public int ID { get; set; }
        public int Make_ID { get; set; }
        public string Model { get; set; }
    }
}
